import pandas as pd
import numpy as np
from src.features.technical import (
    calculate_rsi, calculate_macd, calculate_bollinger_bands, 
    calculate_atr, calculate_ema, calculate_momentum
)

class FeatureEngine:
    def __init__(self):
        pass

    def generate_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Takes a raw OHLCV DataFrame (index=date, cols=[open, high, low, close, volume, adjusted_close])
        Returns a DataFrame with all features added.
        """
        if df.empty:
            return df
        
        # Use adjusted_close for technicals if available, else close
        price_col = 'adjusted_close' if 'adjusted_close' in df.columns else 'close'
        price = df[price_col]
        
        # --- Technical Indicators ---
        
        # RSI
        df['RSI_14'] = calculate_rsi(price, period=14)
        df['RSI_21'] = calculate_rsi(price, period=21)
        
        # MACD
        macd_df = calculate_macd(price)
        df = pd.concat([df, macd_df], axis=1)
        
        # Bollinger Bands
        bb_df = calculate_bollinger_bands(price)
        df = pd.concat([df, bb_df], axis=1)
        
        # ATR
        df['ATR_14'] = calculate_atr(df['high'], df['low'], df['close'], window=14)
        
        # EMAs
        df['EMA_20'] = calculate_ema(price, span=20)
        df['EMA_50'] = calculate_ema(price, span=50)
        df['EMA_200'] = calculate_ema(price, span=200)
        
        # Momentum
        df['mom_1w'] = calculate_momentum(price, period=5)
        df['mom_1m'] = calculate_momentum(price, period=20)
        df['mom_3m'] = calculate_momentum(price, period=60)
        
        # Volume Z-Score (20 day rolling)
        vol_mean = df['volume'].rolling(window=20).mean()
        vol_std = df['volume'].rolling(window=20).std()
        df['vol_z_score'] = (df['volume'] - vol_mean) / vol_std
        
        # --- Fundamental Features (Derived) ---
        # Returns
        df['return_1d'] = price.pct_change(1)
        df['return_5d'] = price.pct_change(5)
        df['return_20d'] = price.pct_change(20)
        
        # Volatility (Annualized - assuming 252 trading days)
        df['volatility_20d'] = df['return_1d'].rolling(window=20).std() * np.sqrt(252)
        
        # --- Market Context Features ---
        # (Requires external market index data - placeholder for now)
        # We can implement relative strength vs Index later if passed in.
        
        # Drop initial NaNs generated by rolling windows
        # or keep them but models handle them?
        # Standard: Drop to ensure clean training data.
        # But we might lose recent data if window is large (200).
        # We'll keep them for now, let model pipeline decide on dropping.
        
        return df

    def add_lagged_features(self, df: pd.DataFrame, features: list, lags: list) -> pd.DataFrame:
        """
        Adds lagged versions of specified features.
        Critical for avoiding look-ahead bias.
        """
        for feature in features:
            if feature not in df.columns:
                continue
            for lag in lags:
                df[f'{feature}_lag_{lag}'] = df[feature].shift(lag)
        return df
